
version: '3'

services:
  fastapi-backend:
    build: fastapi-backend/
    restart: always
    ports:
      - 80:80
    networks:
      - deploy_network  
    container_name: fastapi-backend
    


  streamlit-frontend:
    build: streamlit-frontend/
    restart: always
    depends_on:
      - fastapi-backend   
    ports:
      - 8501:8501
    networks:
      - deploy_network
    container_name: streamlit-frontend


networks:
  deploy_network:
    driver: bridge
    



