channels:
- conda-forge
dependencies:
- python=3.9.13
- pip<=22.3.1
- pip:
  - mlflow<3,>=2.1
  - cffi==1.15.1
  - cloudpickle==2.2.1
  - defusedxml==0.7.1
  - lightgbm==3.3.5
  - psutil==5.9.4
  - scikit-learn==1.2.1
  - typing-extensions==4.3.0
name: mlflow-env
